package gr.james.influence.annotation;

import gr.james.influence.api.graph.Graph;
import gr.james.influence.api.graph.VertexProvider;

import java.lang.annotation.*;

/**
 * A method annotated {@code @AutoGeneratedVertex} indicates a method that internally uses a {@link VertexProvider} to
 * generate a new vertex instance. These methods may throw {@link UnsupportedOperationException} if the underlying
 * {@link Graph} instance does not support these kinds of operations.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface AutoGeneratedVertex {
}
