package gr.james.influence.annotation;

import gr.james.influence.graph.DirectedGraph;
import gr.james.influence.graph.VertexProvider;

import java.lang.annotation.*;

/**
 * A method annotated {@code @AutoGeneratedVertex} indicates a method that internally uses a {@link VertexProvider} to
 * generate a new vertex instance. These methods may throw {@link UnsupportedOperationException} if the underlying
 * {@link DirectedGraph} instance does not support these kinds of operations.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Deprecated
public @interface AutoGeneratedVertex {
}
