package gr.james.influence.annotation;

import gr.james.influence.api.EdgeProvider;
import gr.james.influence.api.Graph;

import java.lang.annotation.*;

/**
 * <p>A method annotated {@code @AutoGeneratedEdge} indicates a method that internally uses an
 * {@link EdgeProvider} to generate a new edge instance. These methods may throw
 * {@link UnsupportedOperationException} if the underlying {@link Graph} instance does not support these kinds of
 * operations.</p>
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface AutoGeneratedEdge {
}
